name: Checkstyle

on:
  push:
    branches:
      - '*'

jobs:
  check:
    # put [skip ci] into the commit message if you don't want to run this workflow

    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up build properties
        run: |
          echo 'licenceKey=""' > local.properties
          echo 'android.useAndroidX=true' >> gradle.properties
          echo 'android.enableJetifier=true' >> gradle.properties

      - name: Run gradle checks
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: check
